version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
     - "8000:8000"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/test.py --master

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/test.py --worker --master-host master